#!/bin/bash
chmod +x /interface_setup
/interface_setup
ip rou del default 2> /dev/null
ip route add default via 10.152.0.254 dev net0

echo "ready! run 'docker exec -it $HOSTNAME /bin/zsh' to attach to this node" >&2
for f in /proc/sys/net/ipv4/conf/*/rp_filter; do echo 0 > "$f"; done
python3.7 /carla/refactor_automatic_control.py --w_ip=${WS_IP} --w_port=${WS_PORT} --host=${CARLA_IP} --port=${CARLA_PORT} --r_name=${ROLE_NAME} --cam=${CAMERA} -l > /seed_car_1.log 2>&1
tail -f /dev/null

